-- Creator OS Phase 1.1: Mina Mosya premium polish
-- The Vercel API also stores settings in analytics_events until this dedicated table is applied.

alter table if exists public.creators
  add column if not exists hero_video_url text not null default '',
  add column if not exists music_enabled boolean not null default false,
  add column if not exists music_url text not null default '',
  add column if not exists music_volume numeric not null default 0.35,
  add column if not exists music_loop boolean not null default true,
  add column if not exists welcome_intro_enabled boolean not null default true,
  add column if not exists background_gradient text not null default '',
  add column if not exists redirect_mina_enabled boolean not null default true,
  add column if not exists discord_link_visible boolean not null default true,
  add column if not exists discord_link_title text not null default 'Discord',
  add column if not exists discord_link_subtitle text not null default 'Community',
  add column if not exists discord_link_cta_label text not null default 'Join',
  add column if not exists tiktok_link_visible boolean not null default true,
  add column if not exists tiktok_link_title text not null default 'TikTok',
  add column if not exists tiktok_link_subtitle text not null default '@mosyaamosya',
  add column if not exists tiktok_link_cta_label text not null default 'Watch',
  add column if not exists battle_link_visible boolean not null default true,
  add column if not exists battle_link_title text not null default 'Prepare for Battle',
  add column if not exists battle_link_subtitle text not null default 'Get your TikTok Coins before the battle begins.',
  add column if not exists battle_link_cta_label text not null default 'Prepare',
  add column if not exists business_link_visible boolean not null default true,
  add column if not exists business_link_title text not null default 'Business',
  add column if not exists business_link_subtitle text not null default 'Booking and collabs',
  add column if not exists business_link_cta_label text not null default 'Email',
  add column if not exists music_link_visible boolean not null default false,
  add column if not exists music_link_title text not null default 'Music',
  add column if not exists music_link_subtitle text not null default 'Mina''s stream soundtrack',
  add column if not exists music_link_cta_label text not null default 'Open',
  add column if not exists newsletter_cta_label text not null default 'Subscribe to the Mailing List',
  add column if not exists community_link_visible boolean not null default true,
  add column if not exists community_link_title text not null default 'Community',
  add column if not exists community_link_subtitle text not null default 'Join Mina''s Discord for stream updates and community drops.',
  add column if not exists community_link_cta_label text not null default 'Join Discord';

insert into public.creators (
  id,
  display_name,
  username,
  slug,
  bio,
  location,
  avatar_url,
  banner_url,
  hero_video_url,
  tiktok_url,
  discord_url,
  instagram_url,
  tiktok_coins_url,
  business_email,
  live_url,
  live_status,
  live_button_text,
  theme_preset,
  subscribe_popup_enabled,
  subscribe_popup_title,
  subscribe_popup_copy,
  music_enabled,
  music_url,
  music_volume,
  music_loop,
  welcome_intro_enabled,
  background_gradient,
  redirect_mina_enabled
) values (
  '11111111-1111-4111-8111-111111111111',
  'Mina Mosya',
  'mosyaamosya',
  'mosyaamosya',
  'Daily livestreams, community, yapping, and soft chaos from Chicago.',
  'Chicago 🇺🇸',
  '/assets/mosyaamosya/profile-v2.jpg',
  '',
  '/assets/mosyaamosya/intro.mp4',
  'https://www.tiktok.com/@mosyaamosya',
  'https://discord.gg/GGE7WsUZR',
  '',
  'https://www.tiktok.com/coin',
  'mina@doneovernight.com',
  '',
  false,
  'Join Live',
  'mina',
  false,
  '',
  '',
  false,
  '',
  0.35,
  true,
  true,
  'radial-gradient(circle at 18% -10%, rgba(255,211,223,.22), transparent 30rem), radial-gradient(circle at 105% 8%, rgba(139,95,74,.24), transparent 28rem), linear-gradient(155deg, #080504 0%, #160b09 42%, #050403 100%)',
  true
) on conflict (id) do update set
  display_name = excluded.display_name,
  username = excluded.username,
  slug = excluded.slug,
  bio = excluded.bio,
  location = excluded.location,
  avatar_url = excluded.avatar_url,
  hero_video_url = excluded.hero_video_url,
  tiktok_url = excluded.tiktok_url,
  instagram_url = excluded.instagram_url,
  tiktok_coins_url = excluded.tiktok_coins_url,
  business_email = excluded.business_email,
  live_url = excluded.live_url,
  live_status = excluded.live_status,
  live_button_text = excluded.live_button_text,
  theme_preset = excluded.theme_preset,
  music_enabled = excluded.music_enabled,
  music_url = excluded.music_url,
  music_volume = excluded.music_volume,
  music_loop = excluded.music_loop,
  welcome_intro_enabled = excluded.welcome_intro_enabled,
  background_gradient = excluded.background_gradient,
  redirect_mina_enabled = excluded.redirect_mina_enabled,
  updated_at = now();
