-- Creator OS: Doonia J seed
-- Applies only the Doonia row and Doonia auth. Mina is intentionally untouched.

alter table if exists public.creators
  add column if not exists hero_video_url text not null default '',
  add column if not exists music_enabled boolean not null default false,
  add column if not exists music_url text not null default '',
  add column if not exists music_volume numeric not null default 0.35,
  add column if not exists music_loop boolean not null default true,
  add column if not exists intro_audio_enabled boolean not null default false,
  add column if not exists intro_audio_url text not null default '',
  add column if not exists intro_audio_volume numeric not null default 0.35,
  add column if not exists intro_audio_fade_out_duration numeric not null default 2,
  add column if not exists intro_audio_stop_after numeric not null default 4,
  add column if not exists welcome_intro_enabled boolean not null default true,
  add column if not exists background_gradient text not null default '',
  add column if not exists redirect_mina_enabled boolean not null default true,
  add column if not exists next_live_datetime timestamptz,
  add column if not exists discord_invite_url text not null default '',
  add column if not exists discord_server_id text not null default '',
  add column if not exists creator_dna text not null default 'streamer',
  add column if not exists tiktok_live_username text not null default '',
  add column if not exists auto_live_detection_enabled boolean not null default true,
  add column if not exists manual_live_fallback_enabled boolean not null default true,
  add column if not exists battle_mode_enabled boolean not null default false,
  add column if not exists battle_opponent text not null default '',
  add column if not exists battle_result text not null default '',
  add column if not exists battle_win_streak integer not null default 0,
  add column if not exists battle_updated_at timestamptz,
  add column if not exists battle_undo_snapshot text not null default '',
  add column if not exists pinned_block text not null default '',
  add column if not exists community_state text not null default 'open',
  add column if not exists quick_announcement text not null default '',
  add column if not exists quick_poll text not null default '',
  add column if not exists faq_visible boolean not null default true,
  add column if not exists discord_visible boolean not null default true,
  add column if not exists creator_passport_visible boolean not null default true,
  add column if not exists discord_link_visible boolean not null default true,
  add column if not exists discord_link_title text not null default 'Discord',
  add column if not exists discord_link_subtitle text not null default 'Community',
  add column if not exists discord_link_cta_label text not null default 'Join',
  add column if not exists tiktok_link_visible boolean not null default true,
  add column if not exists tiktok_link_title text not null default 'TikTok',
  add column if not exists tiktok_link_subtitle text not null default '',
  add column if not exists tiktok_link_cta_label text not null default 'Watch',
  add column if not exists battle_link_visible boolean not null default true,
  add column if not exists battle_link_title text not null default 'Prepare for Battle',
  add column if not exists battle_link_subtitle text not null default 'Get your TikTok Coins before the battle begins.',
  add column if not exists battle_link_cta_label text not null default 'Prepare',
  add column if not exists business_link_visible boolean not null default true,
  add column if not exists business_link_title text not null default 'Business',
  add column if not exists business_link_subtitle text not null default 'Booking and collabs',
  add column if not exists business_link_cta_label text not null default 'Email',
  add column if not exists music_link_visible boolean not null default false,
  add column if not exists music_link_title text not null default 'Music',
  add column if not exists music_link_subtitle text not null default '',
  add column if not exists music_link_cta_label text not null default 'Open',
  add column if not exists newsletter_cta_label text not null default 'Subscribe',
  add column if not exists newsletter_destination text not null default '',
  add column if not exists faq_link_visible boolean not null default false,
  add column if not exists faq_link_title text not null default 'FAQ',
  add column if not exists faq_link_subtitle text not null default 'Questions and answers',
  add column if not exists faq_link_cta_label text not null default 'Open',
  add column if not exists faq_link_url text not null default '',
  add column if not exists community_link_visible boolean not null default true,
  add column if not exists community_link_title text not null default 'Community',
  add column if not exists community_link_subtitle text not null default '',
  add column if not exists community_link_cta_label text not null default 'Join',
  add column if not exists community_link_url text not null default '',
  add column if not exists share_link_visible boolean not null default true,
  add column if not exists custom_links jsonb not null default '[]'::jsonb;

create table if not exists public.creator_auth (
  creator_id uuid primary key references public.creators(id) on delete cascade,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.creators (
  id, display_name, username, slug, bio, location, avatar_url, banner_url, hero_video_url,
  tiktok_url, discord_url, instagram_url, tiktok_coins_url, business_email, live_url,
  live_status, live_button_text, theme_preset, subscribe_popup_enabled, subscribe_popup_title,
  subscribe_popup_copy, music_enabled, music_url, music_volume, music_loop, intro_audio_enabled,
  intro_audio_url, intro_audio_volume, intro_audio_fade_out_duration, intro_audio_stop_after,
  welcome_intro_enabled, background_gradient, redirect_mina_enabled, next_live_datetime,
  discord_invite_url, discord_server_id, creator_dna, tiktok_live_username,
  auto_live_detection_enabled, manual_live_fallback_enabled, battle_mode_enabled, battle_opponent,
  battle_result, battle_win_streak, battle_updated_at, battle_undo_snapshot, pinned_block,
  community_state, quick_announcement, quick_poll, faq_visible, discord_visible,
  creator_passport_visible, discord_link_visible, discord_link_title, discord_link_subtitle,
  discord_link_cta_label, tiktok_link_visible, tiktok_link_title, tiktok_link_subtitle,
  tiktok_link_cta_label, battle_link_visible, battle_link_title, battle_link_subtitle,
  battle_link_cta_label, business_link_visible, business_link_title, business_link_subtitle,
  business_link_cta_label, music_link_visible, music_link_title, music_link_subtitle,
  music_link_cta_label, newsletter_cta_label, newsletter_destination, faq_link_visible,
  faq_link_title, faq_link_subtitle, faq_link_cta_label, faq_link_url, community_link_visible,
  community_link_title, community_link_subtitle, community_link_cta_label, community_link_url,
  share_link_visible, custom_links
) values (
  '22222222-2222-4222-8222-222222222222', 'Doonia J', 'doonia.j', 'doonia',
  'Fitness, discipline, and premium training energy.', '', '/assets/doonia/profile-placeholder.svg',
  '/assets/doonia/hero-placeholder.svg', '', 'https://www.tiktok.com/@doonia.j', '',
  'https://www.instagram.com/doonia.j/', 'https://www.tiktok.com/coin', '', '', false,
  'Next Workout', 'doonia', false, '', '', false, '', 0.35, true, false, '', 0.35, 2, 4,
  true, 'radial-gradient(circle at 18% -10%, rgba(212,160,76,.24), transparent 30rem), radial-gradient(circle at 105% 8%, rgba(126,82,36,.26), transparent 28rem), linear-gradient(155deg, #030303 0%, #120d08 46%, #050403 100%)',
  false, null, '', '', 'coach', 'doonia.j', true, true, false, '', '', 0, null, '', '',
  'preview', '', '', false, false, true, false, 'Community', 'Join the team.', 'Join',
  true, 'TikTok', '@doonia.j', 'Watch', true, 'Prepare for Battle',
  'Get your TikTok Coins before the live battle begins.', 'Prepare', true, 'Business',
  'Partnerships and collabs.', 'Contact', false, 'Gym Playlist', 'Coming soon.', 'Listen',
  'Subscribe', '', false, '7-Day Challenge', 'Coming soon.', 'Start', '', true,
  'Community', 'Join the team.', 'Join', '', true,
  '[
    {"id":"legion","visible":true,"title":"Workout Supplements","subtitle":"Legion Athletics - use code DOONIA.","cta_label":"Shop Legion","url":"https://legionathletics.rfrl.co/rnpon"},
    {"id":"kontrolled-insanity","visible":true,"title":"Kontrolled Insanity","subtitle":"Official brand - use code DOONIA.","cta_label":"Shop","url":"https://kontrolledinsanity.com/?aff=88"},
    {"id":"amazon","visible":true,"title":"Amazon Storefront","subtitle":"Gym essentials and favorites.","cta_label":"Shop","url":"https://a.co/d/04e5e97O"},
    {"id":"youtube","visible":true,"title":"YouTube","subtitle":"Doonia J","cta_label":"Watch","url":"https://www.youtube.com/@doonia.j"},
    {"id":"support","visible":true,"title":"Support Me","subtitle":"Every contribution helps me create more content.","cta_label":"Support","url":""},
    {"id":"coach-doonia-ai","visible":false,"title":"Coach Doonia AI","subtitle":"Coming soon.","cta_label":"Open","url":""},
    {"id":"weekly-challenge","visible":false,"title":"Weekly Challenge","subtitle":"Coming soon.","cta_label":"Join","url":""},
    {"id":"daily-motivation","visible":false,"title":"Daily Motivation","subtitle":"Coming soon.","cta_label":"Read","url":""},
    {"id":"gym-playlist","visible":false,"title":"Gym Playlist","subtitle":"Coming soon.","cta_label":"Listen","url":""},
    {"id":"my-setup","visible":false,"title":"My Setup","subtitle":"Coming soon.","cta_label":"View","url":""},
    {"id":"7-day-challenge","visible":false,"title":"7-Day Challenge","subtitle":"Coming soon.","cta_label":"Start","url":""}
  ]'::jsonb
) on conflict (id) do update set
  display_name = excluded.display_name,
  username = excluded.username,
  slug = excluded.slug,
  bio = excluded.bio,
  avatar_url = excluded.avatar_url,
  banner_url = excluded.banner_url,
  tiktok_url = excluded.tiktok_url,
  instagram_url = excluded.instagram_url,
  tiktok_coins_url = excluded.tiktok_coins_url,
  theme_preset = excluded.theme_preset,
  creator_dna = excluded.creator_dna,
  tiktok_live_username = excluded.tiktok_live_username,
  battle_link_title = excluded.battle_link_title,
  battle_link_subtitle = excluded.battle_link_subtitle,
  battle_link_cta_label = excluded.battle_link_cta_label,
  business_link_title = excluded.business_link_title,
  business_link_subtitle = excluded.business_link_subtitle,
  business_link_cta_label = excluded.business_link_cta_label,
  custom_links = excluded.custom_links,
  updated_at = now();

insert into public.creator_auth (creator_id, password_hash, updated_at)
values (
  '22222222-2222-4222-8222-222222222222',
  'pbkdf2_sha256$120000$7yY7P1AHcbp0qP_kDeo8Yw$QHvrQesKUIp1LakBxxCI73o1-yEXonDqHedJH_XZTns',
  now()
) on conflict (creator_id) do nothing;
