const crypto = require("node:crypto");
const repository = require("./repository");
const service = require("./service");
const autonomy = require("./autonomy");
const { clean, getConfig } = require("./config");
const { sendTelegramMessage, editTelegramMessage, answerTelegramCallbackQuery } = require("../../heartbeat/telegram");
const { parseBody, send } = require("./http");

const CALLBACK_TTL_MS = 15 * 60_000;
const REJECT_REASONS = ["Too much summary", "No original insight", "Too technical", "Too generic", "Weak hook", "Weak ending", "Low repost potential", "Low save potential", "Poor brand alignment", "Topic fatigue", "Duplicate idea", "Other"];
const DASHBOARD_URL = "https://admin.doneovernight.com/x-content";

function csv(value) { return new Set(String(value || "").split(",").map((item) => item.trim()).filter(Boolean)); }
function controlConfig(env = process.env) {
  return {
    botToken: clean(env.TELEGRAM_BOT_TOKEN),
    chatIds: csv(env.TELEGRAM_X_ADMIN_CHAT_IDS),
    userIds: csv(env.TELEGRAM_X_ADMIN_USER_IDS),
    webhookSecret: clean(env.TELEGRAM_WEBHOOK_SECRET),
    signingSecret: clean(env.TELEGRAM_CONTROL_SECRET || env.CRON_SECRET || env.CONTENT_CRON_SECRET),
    dashboardUrl: clean(env.X_CONTENT_DASHBOARD_URL) || DASHBOARD_URL
  };
}
function safeEqual(one, two) { const a = Buffer.from(String(one || "")); const b = Buffer.from(String(two || "")); return a.length === b.length && crypto.timingSafeEqual(a, b); }
function isAllowedAdmin(chatId, userId, config) { return Boolean(config?.chatIds?.has(String(chatId)) && config?.userIds?.has(String(userId))); }
function webhookAuthorized(req, config) { return Boolean(config.webhookSecret && safeEqual(req.headers?.["x-telegram-bot-api-secret-token"], config.webhookSecret)); }
function signature(token, expiresAt, secret) { return crypto.createHmac("sha256", secret).update(`${token}:${expiresAt}`).digest("base64url").slice(0, 12); }
function callbackData(event, config) { return `tc.${event.callback_token}.${signature(event.callback_token, event.expires_at, config.signingSecret)}`; }
function parseCallback(value) { const match = /^tc\.([A-Za-z0-9_-]{8,64})\.([A-Za-z0-9_-]{8,24})$/.exec(String(value || "")); return match ? { token: match[1], signature: match[2] } : null; }
function button(text, callback_data) { return { text, callback_data }; }
function linkButton(text, url) { return { text, url }; }
function score(value) { return Number.isFinite(Number(value)) ? Number(value).toFixed(2) : "—"; }
function truncate(value, length = 220) { const text = String(value || "").trim(); return text.length > length ? `${text.slice(0, length - 1)}…` : text; }
function detailsFromDraft(draft, candidate = null, decision = null, schedule = null) {
  const v2 = draft.model_output?.v2 || {}; const scores = v2.scores || draft.model_output?.scores || {};
  return {
    text: String(draft.text || ""), weighted: Number(draft.weighted_character_count || 0), format: v2.format_label || v2.format || draft.post_type || "Post", topic: draft.topic_cluster || candidate?.topic_cluster || "—",
    source: candidate?.headline || draft.source_references?.[0] || "Official source", sourceUrl: candidate?.source_url || draft.source_references?.[0] || "",
    objective: decision?.objective || "authority", insight: score(scores.insight), save: score(scores.save), repost: score(scores.repost), educational: score(scores.educational), brand: score(scores.brand), predicted: score(decision?.predicted_performance || scores.quality || draft.quality_score),
    decision: decision?.decision || "human review", schedule: schedule?.scheduled_for || decision?.scheduled_for || "Not proposed", blocks: decision?.blocking_thresholds || []
  };
}
function reviewText(draft, candidate, decision, schedule, state = "QUEUED", history = "") {
  const d = detailsFromDraft(draft, candidate, decision, schedule);
  return [`${state}`, "", d.text, "", `Weighted: ${d.weighted}`, `Format: ${d.format}`, `Topic: ${d.topic}`, `Source: ${truncate(d.source)}`, d.sourceUrl ? d.sourceUrl : null, `Objective: ${d.objective}`, `Scores: insight ${d.insight} · save ${d.save} · repost ${d.repost}`, `Educational: ${d.educational} · Brand: ${d.brand} · Predicted: ${d.predicted}`, `Autonomy: ${d.decision}`, `Proposed: ${d.schedule}`, d.blocks.length ? `Blocks: ${d.blocks.join(", ")}` : null, history].filter(Boolean).join("\n");
}
async function createEvent(repo, action, { draftId = null, chatId, userId, payload = {}, expiresAt = new Date(Date.now() + CALLBACK_TTL_MS).toISOString() }) {
  const callback_token = crypto.randomBytes(12).toString("base64url");
  return repo.createTelegramControlEvent({ callback_token, action, draft_id: draftId, chat_id: String(chatId), user_id: String(userId), payload, expires_at: expiresAt });
}
async function callback(repo, action, context, config, payload = {}) { const event = await createEvent(repo, action, { ...context, payload }); return callbackData(event, config); }
async function attachEvents(repo, callbacks, messageId) { await Promise.all(callbacks.map((item) => repo.attachTelegramMessage(item.token, messageId).catch(() => null))); }
async function actionsForDraft(repo, draft, context, config, state = "queued", replacementFor = null) {
  if (state === "approved") {
    const publish = await createEvent(repo, "publish_start", { ...context, draftId: draft.id }); const undo = await createEvent(repo, "undo_approval", { ...context, draftId: draft.id });
    return { events: [publish, undo], markup: { inline_keyboard: [[button("Publish now", callbackData(publish, config)), button("Undo approval", callbackData(undo, config))], [linkButton("Open dashboard", config.dashboardUrl)]] } };
  }
  if (state === "regenerated") {
    const approve = await createEvent(repo, "approve", { ...context, draftId: draft.id }); const reject = await createEvent(repo, "reject_start", { ...context, draftId: draft.id }); const regenerate = await createEvent(repo, "regenerate", { ...context, draftId: draft.id }); const keep = await createEvent(repo, "keep_original", { ...context, draftId: draft.id, payload: { original_draft_id: replacementFor } });
    return { events: [approve, reject, regenerate, keep], markup: { inline_keyboard: [[button("Approve new", callbackData(approve, config)), button("Reject new", callbackData(reject, config))], [button("Regenerate again", callbackData(regenerate, config)), button("Keep original", callbackData(keep, config))], [linkButton("Open dashboard", config.dashboardUrl)]] } };
  }
  const approve = await createEvent(repo, "approve", { ...context, draftId: draft.id }); const reject = await createEvent(repo, "reject_start", { ...context, draftId: draft.id }); const regenerate = await createEvent(repo, "regenerate", { ...context, draftId: draft.id }); const schedule = await createEvent(repo, "schedule_menu", { ...context, draftId: draft.id });
  return { events: [approve, reject, regenerate, schedule], markup: { inline_keyboard: [[button("Approve", callbackData(approve, config)), button("Reject", callbackData(reject, config))], [button("Regenerate", callbackData(regenerate, config)), button("Schedule", callbackData(schedule, config))], [linkButton("Open dashboard", config.dashboardUrl)]] } };
}
async function reviewCard({ repo = repository, transport = { sendTelegramMessage }, draft, chatId, userId, config = controlConfig(), candidate = null, decision = null, schedule = null, state = "QUEUED", replacementFor = null, history = "" }) {
  if (!config.botToken || !config.signingSecret || !isAllowedAdmin(chatId, userId, config)) return { sent: false, skipped: "Telegram Control is not configured for this admin" };
  const context = { chatId, userId }; const actions = await actionsForDraft(repo, draft, context, config, state.toLowerCase(), replacementFor);
  const sent = await transport.sendTelegramMessage({ botToken: config.botToken, chatId, text: reviewText(draft, candidate, decision, schedule, state, history), replyMarkup: actions.markup });
  if (sent.sent && sent.messageId) await attachEvents(repo, actions.events, sent.messageId);
  return { ...sent, state, callbacks: actions.events.map((event) => event.callback_token) };
}
async function getDraftContext(repo, draftId) {
  const draft = await repo.getDraft(draftId); if (!draft) throw new Error("Draft no longer exists");
  const [candidate, decision, schedules] = await Promise.all([draft.candidate_id ? repo.getCandidate(draft.candidate_id).catch(() => null) : null, repo.latestDecisionForDraft?.(draft.id).catch(() => null), repo.listAutonomySchedules?.(100).catch(() => [])]);
  return { draft, candidate, decision, schedule: (schedules || []).find((row) => row.draft_id === draft.id && !["cancelled", "published"].includes(row.status)) || null };
}
async function editCard(transport, config, chatId, messageId, text, replyMarkup) { if (!messageId) return null; return transport.editTelegramMessage({ botToken: config.botToken, chatId, messageId, text, replyMarkup }); }
function recommendedSlot() { const now = new Date(); return new Date(now.getTime() + 2 * 60 * 60_000).toISOString(); }
function amsterdamTomorrow(hour = 10) { const now = new Date(); const local = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Amsterdam", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(now); const p = Object.fromEntries(local.map((part) => [part.type, part.value])); const next = new Date(Date.UTC(Number(p.year), Number(p.month) - 1, Number(p.day) + 1)); return amsterdamToIso(`${next.getUTCFullYear()}-${String(next.getUTCMonth() + 1).padStart(2, "0")}-${String(next.getUTCDate()).padStart(2, "0")} ${String(hour).padStart(2, "0")}:00`); }
function amsterdamToIso(value) { const match = /^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})$/.exec(String(value || "").trim()); if (!match) return null; const target = Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]), Number(match[4]), Number(match[5])); const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Europe/Amsterdam", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(target)); const local = Object.fromEntries(parts.filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); const observed = Date.UTC(Number(local.year), Number(local.month) - 1, Number(local.day), Number(local.hour), Number(local.minute)); const result = new Date(target - (observed - target)); return Number.isFinite(result.getTime()) ? result.toISOString() : null; }
async function audit(repo, eventType, event, payload = {}) { return repo.recordAutonomyAudit?.({ event_type: `telegram_${eventType}`, draft_id: event.draft_id || null, payload: { ...payload, operator: "telegram_admin" } }).catch(() => null); }
async function handleAction(event, update, deps) {
  const { repo, svc, transport, config } = deps; const chatId = String(update.callback_query.message?.chat?.id || event.chat_id); const messageId = update.callback_query.message?.message_id || event.message_id; const context = { chatId, userId: String(update.callback_query.from?.id) };
  const current = event.draft_id ? await getDraftContext(repo, event.draft_id) : null;
  if (event.action === "approve") { const approved = await svc.approveDraft(event.draft_id, { operator: "telegram_admin", metadata: { channel: "telegram" } }); const actions = await actionsForDraft(repo, approved, context, config, "approved"); await attachEvents(repo, actions.events, messageId); await editCard(transport, config, chatId, messageId, reviewText(approved, current.candidate, current.decision, current.schedule, "APPROVED", "Approved in Telegram"), actions.markup); await audit(repo, "approve", event); return { action: "approved" }; }
  if (event.action === "undo_approval") { const updated = await repo.updateDraft(event.draft_id, { status: "queued", approved_at: null }); const actions = await actionsForDraft(repo, updated, context, config, "queued"); await attachEvents(repo, actions.events, messageId); await editCard(transport, config, chatId, messageId, reviewText(updated, current.candidate, current.decision, current.schedule, "QUEUED", "Approval undone in Telegram"), actions.markup); await audit(repo, "undo_approval", event); return { action: "approval_undone" }; }
  if (event.action === "reject_start") { const events = await Promise.all(REJECT_REASONS.map((reason) => createEvent(repo, "reject_reason", { ...context, draftId: event.draft_id, payload: { reason } }))); await attachEvents(repo, events, messageId); const rows = []; for (let i = 0; i < events.length; i += 2) rows.push(events.slice(i, i + 2).map((item) => button(item.payload.reason, callbackData(item, config)))); await editCard(transport, config, chatId, messageId, `${reviewText(current.draft, current.candidate, current.decision, current.schedule, "REJECT — SELECT REASON")}\n\nOptional note: reply to this message with /note your context before choosing a reason.`, { inline_keyboard: rows.concat([[linkButton("Open dashboard", config.dashboardUrl)]]) }); return { action: "reject_reason_requested" }; }
  if (event.action === "reject_reason") { const reason = event.payload?.reason; const rejected = await svc.rejectDraft(event.draft_id, { reasons: [reason], comments: event.notes || "", operator: "telegram_admin", metadata: { channel: "telegram" } }); await editCard(transport, config, chatId, messageId, reviewText(rejected, current.candidate, current.decision, current.schedule, "REJECTED", `Reason: ${reason}${event.notes ? `\nNote: ${truncate(event.notes, 500)}` : ""}`), { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); await audit(repo, "reject", event, { reason }); return { action: "rejected", reason }; }
  if (event.action === "regenerate") { const result = await svc.regenerateDraft(event.draft_id, { reasons: ["Other"], comments: "Telegram regeneration request", operator: "telegram_admin", metadata: { channel: "telegram" } }); const next = result.draft || await repo.getDraft(result.id); await editCard(transport, config, chatId, messageId, reviewText(current.draft, current.candidate, current.decision, current.schedule, "REGENERATED", "Original retained as learning history."), { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); const card = await reviewCard({ repo, transport, draft: next, chatId, userId: context.userId, config, candidate: current.candidate, state: "REGENERATED", replacementFor: current.draft.id, history: `Before: ${truncate(current.draft.text, 260)}\n\nAfter is shown above.` }); await audit(repo, "regenerate", event, { replacement_draft_id: next?.id || null }); return { action: "regenerated", replacement: next?.id || null, card_sent: card.sent }; }
  if (event.action === "keep_original") { const original = await repo.getDraft(event.payload?.original_draft_id); if (!original) throw new Error("Original draft is unavailable"); await repo.updateDraft(event.draft_id, { status: "rejected", rejection_reason: "Replacement declined; original restored from Telegram" }); const restored = await repo.updateDraft(original.id, { status: "queued", rejection_reason: null }); const actions = await actionsForDraft(repo, restored, context, config, "queued"); await attachEvents(repo, actions.events, messageId); await editCard(transport, config, chatId, messageId, reviewText(restored, current.candidate, current.decision, current.schedule, "QUEUED", "Original restored in Telegram."), actions.markup); await audit(repo, "keep_original", event, { original_draft_id: original.id }); return { action: "original_restored" }; }
  if (event.action === "schedule_menu") { const times = { recommended: recommendedSlot(), today: new Date(Date.now() + 3 * 60 * 60_000).toISOString(), tomorrow: amsterdamTomorrow() }; const entries = await Promise.all(Object.entries(times).map(async ([kind, at]) => createEvent(repo, `schedule_${kind}`, { ...context, draftId: event.draft_id, payload: { scheduled_for: at } }))); const custom = await createEvent(repo, "schedule_custom", { ...context, draftId: event.draft_id }); const cancel = await createEvent(repo, "schedule_cancel", { ...context, draftId: event.draft_id }); await attachEvents(repo, [...entries, custom, cancel], messageId); await editCard(transport, config, chatId, messageId, `${reviewText(current.draft, current.candidate, current.decision, current.schedule, "SCHEDULE — EUROPE/AMSTERDAM")}\n\nShadow mode records a shadow schedule only.`, { inline_keyboard: [[button("Recommended", callbackData(entries[0], config)), button("Today", callbackData(entries[1], config))], [button("Tomorrow", callbackData(entries[2], config)), button("Custom time", callbackData(custom, config))], [button("Cancel", callbackData(cancel, config))], [linkButton("Open dashboard", config.dashboardUrl)]] }); return { action: "schedule_requested" }; }
  if (event.action === "schedule_custom") { await editCard(transport, config, chatId, messageId, `${reviewText(current.draft, current.candidate, current.decision, current.schedule, "CUSTOM SCHEDULE — EUROPE/AMSTERDAM")}\n\nReply to this message: /schedule YYYY-MM-DD HH:MM`, { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); return { action: "custom_schedule_requested" }; }
  if (["schedule_recommended", "schedule_today", "schedule_tomorrow"].includes(event.action)) { const schedule = await svc.scheduleDraft(event.draft_id, event.payload.scheduled_for, { operator: "telegram_admin" }); await editCard(transport, config, chatId, messageId, reviewText(current.draft, current.candidate, current.decision, schedule, schedule.status === "shadow" ? "SHADOW SCHEDULED" : "SCHEDULED", `Scheduled for ${schedule.scheduled_for}`), { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); await audit(repo, "schedule", event, { scheduled_for: schedule.scheduled_for, status: schedule.status }); return { action: "scheduled", status: schedule.status }; }
  if (event.action === "schedule_cancel") { if (current.schedule?.id) await repo.updateAutonomySchedule(current.schedule.id, { status: "cancelled" }); await editCard(transport, config, chatId, messageId, reviewText(current.draft, current.candidate, current.decision, current.schedule, "CANCELLED", "Scheduling cancelled; draft remains in review."), { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); await audit(repo, "schedule_cancel", event); return { action: "schedule_cancelled" }; }
  if (event.action === "publish_start") { const confirm = await createEvent(repo, "publish_confirm", { ...context, draftId: event.draft_id }); const cancel = await createEvent(repo, "publish_cancel", { ...context, draftId: event.draft_id }); await attachEvents(repo, [confirm, cancel], messageId); await editCard(transport, config, chatId, messageId, `${reviewText(current.draft, current.candidate, current.decision, current.schedule, "CONFIRM PUBLISH")}\n\nPublish this approved post now?`, { inline_keyboard: [[button("Confirm publish", callbackData(confirm, config)), button("Cancel", callbackData(cancel, config))]] }); return { action: "publish_confirmation_requested" }; }
  if (event.action === "publish_cancel") { const actions = await actionsForDraft(repo, current.draft, context, config, "approved"); await attachEvents(repo, actions.events, messageId); await editCard(transport, config, chatId, messageId, reviewText(current.draft, current.candidate, current.decision, current.schedule, "APPROVED", "Publish cancelled."), actions.markup); await audit(repo, "publish_cancel", event); return { action: "publish_cancelled" }; }
  if (event.action === "publish_confirm") { const result = await svc.publishApprovedDraft(event.draft_id, { operator: "telegram_admin", metadata: { channel: "telegram", double_confirmed: true } }); const state = result.published ? "PUBLISHED" : "BLOCKED"; await editCard(transport, config, chatId, messageId, reviewText(current.draft, current.candidate, current.decision, current.schedule, state, result.published ? result.url : `No post sent: ${result.skipped || "publication guard"}`), { inline_keyboard: [[linkButton("Open dashboard", config.dashboardUrl)]] }); await audit(repo, "publish", event, { published: Boolean(result.published) }); return { action: "publish", published: Boolean(result.published) }; }
  if (event.action === "control_status") return { action: "status", status: await svc.autonomyStatus() };
  if (event.action === "control_discovery") return { action: "discovery", result: await svc.discover() };
  if (event.action === "control_autonomy") return { action: "autonomy", result: await svc.autonomyDecisionCycle() };
  if (event.action === "control_review_next") { const draft = (await repo.listDrafts()).find((row) => row.status === "queued"); return draft ? { action: "review_next", card: await reviewCard({ repo, transport, draft, chatId, userId: context.userId, config, state: "QUEUED" }) } : { action: "review_next", skipped: "No queued draft" }; }
  if (event.action === "control_publish_queue") return { action: "publish_queue", count: (await repo.listDrafts()).filter((row) => row.status === "approved").length };
  const pauseKeys = { control_pause_discovery: "x_pause_discovery", control_pause_drafting: "x_pause_drafting", control_pause_scheduling: "x_autonomy_paused", control_pause_replies: "x_pause_reply_sync" };
  if (pauseKeys[event.action]) { const confirm = await createEvent(repo, "control_pause_confirm", { ...context, payload: { key: pauseKeys[event.action] } }); await repo.attachTelegramMessage(confirm.callback_token, messageId).catch(() => null); await editCard(transport, config, chatId, messageId, `Confirm pause: ${event.action.replace("control_pause_", "").replace("_", " ")}?`, { inline_keyboard: [[button("Confirm pause", callbackData(confirm, config)), linkButton("Open dashboard", config.dashboardUrl)]] }); return { action: "pause_confirmation_requested" }; }
  if (event.action === "control_pause_confirm") { const key = String(event.payload?.key || ""); if (!new Set(Object.values(pauseKeys)).has(key)) throw new Error("Unsupported pause control"); await repo.setSetting(key, "true"); await audit(repo, "pause", event, { key }); return { action: "paused", key }; }
  if (event.action === "control_kill_start") { const confirm = await createEvent(repo, "control_kill_confirm", context); await repo.attachTelegramMessage(confirm.callback_token, messageId).catch(() => null); await editCard(transport, config, chatId, messageId, "Confirm kill switch? Autonomous scheduling remains stopped until it is cleared in the Command Center.", { inline_keyboard: [[button("Activate kill switch", callbackData(confirm, config)), linkButton("Open dashboard", config.dashboardUrl)]] }); return { action: "kill_confirmation_requested" }; }
  if (event.action === "control_kill_confirm") { await repo.setSetting("x_autonomy_safe_stop", "true"); await audit(repo, "kill_switch", event); return { action: "kill_switch_activated" }; }
  throw new Error("Unsupported Telegram control action");
}
async function controlPanel({ repo = repository, transport = { sendTelegramMessage }, chatId, userId, config = controlConfig() }) {
  if (!config.botToken || !config.signingSecret || !isAllowedAdmin(chatId, userId, config)) return { sent: false, skipped: "Telegram Control is not configured for this admin" };
  const context = { chatId, userId }; const status = await createEvent(repo, "control_status", context); const discovery = await createEvent(repo, "control_discovery", context); const autonomyRun = await createEvent(repo, "control_autonomy", context); const review = await createEvent(repo, "control_review_next", context); const queue = await createEvent(repo, "control_publish_queue", context); const pauseDiscovery = await createEvent(repo, "control_pause_discovery", context); const pauseDrafting = await createEvent(repo, "control_pause_drafting", context); const pauseScheduling = await createEvent(repo, "control_pause_scheduling", context); const pauseReplies = await createEvent(repo, "control_pause_replies", context); const kill = await createEvent(repo, "control_kill_start", context);
  const all = [status, discovery, autonomyRun, review, queue, pauseDiscovery, pauseDrafting, pauseScheduling, pauseReplies, kill];
  const sent = await transport.sendTelegramMessage({ botToken: config.botToken, chatId, text: "DONEOVERNIGHT X Control\nPublishing is approval-gated. Shadow autonomy cannot publish.", replyMarkup: { inline_keyboard: [[button("Status", callbackData(status, config)), button("Run discovery", callbackData(discovery, config))], [button("Run autonomy", callbackData(autonomyRun, config)), button("Review next", callbackData(review, config))], [button("Publish queue", callbackData(queue, config))], [button("Pause discovery", callbackData(pauseDiscovery, config)), button("Pause drafting", callbackData(pauseDrafting, config))], [button("Pause scheduling", callbackData(pauseScheduling, config)), button("Pause replies", callbackData(pauseReplies, config))], [button("Activate kill switch", callbackData(kill, config))], [linkButton("Open dashboard", config.dashboardUrl)]] } });
  if (sent.sent && sent.messageId) await attachEvents(repo, all, sent.messageId); return sent;
}
async function webhook(req, res, deps = {}) {
  const repo = deps.repository || repository; const svc = deps.service || service; const transport = deps.transport || { sendTelegramMessage, editTelegramMessage, answerTelegramCallbackQuery }; const config = deps.config || controlConfig();
  if (req.method !== "POST") return send(res, 405, { success: false, error: "Method not allowed" });
  if (!webhookAuthorized(req, config)) return send(res, 401, { success: false, error: "Telegram webhook unauthorized" });
  const update = await parseBody(req);
  const callbackQuery = update?.callback_query;
  if (callbackQuery?.id) await transport.answerTelegramCallbackQuery({ botToken: config.botToken, callbackQueryId: callbackQuery.id, text: "Processing" }).catch(() => null);
  const chatId = callbackQuery?.message?.chat?.id ?? update?.message?.chat?.id; const userId = callbackQuery?.from?.id ?? update?.message?.from?.id;
  if (!isAllowedAdmin(chatId, userId, config)) return send(res, 200, { success: true, ignored: "unauthorized_telegram_admin" });
  if (update?.message?.text?.trim() === "/x") { const result = await controlPanel({ repo, transport, chatId: String(chatId), userId: String(userId), config }); return send(res, 200, { success: true, result: { sent: result.sent } }); }
  if (update?.message?.text?.startsWith("/note ") && update.message.reply_to_message?.message_id) { const messageId = update.message.reply_to_message.message_id; const notes = update.message.text.slice(6); const event = await repo.latestTelegramControlForMessage(String(chatId), messageId); if (event) { await repo.addTelegramControlNote(event.id, notes); await repo.addTelegramRejectNoteForMessage?.(String(chatId), messageId, notes); } return send(res, 200, { success: true, result: { noted: Boolean(event) } }); }
  if (update?.message?.text?.startsWith("/schedule ") && update.message.reply_to_message?.message_id) { const event = await repo.latestTelegramControlForMessage(String(chatId), update.message.reply_to_message.message_id); const scheduledFor = amsterdamToIso(update.message.text.slice(10)); if (!event?.draft_id || !scheduledFor || new Date(scheduledFor).getTime() <= Date.now()) return send(res, 200, { success: true, result: { scheduled: false } }); const schedule = await svc.scheduleDraft(event.draft_id, scheduledFor, { operator: "telegram_admin", metadata: { channel: "telegram", timezone: "Europe/Amsterdam" } }); await audit(repo, "schedule", event, { scheduled_for: schedule.scheduled_for, status: schedule.status }); return send(res, 200, { success: true, result: { scheduled: true, status: schedule.status } }); }
  if (!callbackQuery) return send(res, 200, { success: true, ignored: "unhandled_update" });
  const parsed = parseCallback(callbackQuery.data); if (!parsed) return send(res, 200, { success: true, ignored: "invalid_callback" });
  const event = await repo.getTelegramControlEvent(parsed.token); if (!event || !config.signingSecret || !safeEqual(parsed.signature, signature(event.callback_token, event.expires_at, config.signingSecret)) || new Date(event.expires_at).getTime() <= Date.now() || String(event.chat_id) !== String(chatId) || String(event.user_id) !== String(userId)) return send(res, 200, { success: true, ignored: "invalid_or_expired_callback" });
  const consumed = await repo.consumeTelegramControlEvent(event.callback_token, { received_at: new Date().toISOString() }); if (!consumed) return send(res, 200, { success: true, ignored: "replayed_callback" });
  try { const result = await handleAction({ ...event, ...consumed }, update, { repo, svc, transport, config }); return send(res, 200, { success: true, result }); }
  catch (error) { await audit(repo, "failed", event, { code: error.code || "TELEGRAM_CONTROL_FAILED" }); return send(res, 200, { success: true, result: { error: "Telegram action could not be completed" } }); }
}

module.exports = { REJECT_REASONS, controlConfig, isAllowedAdmin, webhookAuthorized, parseCallback, callbackData, reviewText, reviewCard, controlPanel, webhook, handleAction, amsterdamTomorrow, amsterdamToIso };
